[package]
name = "duflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "duflow"
path = "src/main.rs"

[dependencies]
duflow-core = { path = "../duflow-core" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4.6", features = ["unstable-dynamic"] }
